### ISSUE TITLE
would like option to change size of panes in MethodBrowse (and others)

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#1]
From the scroll bar you can tell that the method source is not all visible and in these cases it would be useful to drag the source pan up to the near the top of the window ... just a reminder if it is already on your todo list ... Sorta wanted you to know that I'm putting JfP to good use and it is now running on rogue, so I will be prepared to demo ...
 ![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/4580d487-eee9-4a4e-ade2-7343ecdaf3e4)

**Comment by ericwinger** [comment]
Spec2's ability to resize panes is not stellar. I was able to put splitters between the panes on the method list browser and other places that use a table layout like the console. It might be good enough.  

The browser is problematic but I did put splitters between the project/package panes & the category/method panes. The latter don't work nicely but may be better than nothing. 

Leaving open for future work. 

https://github.com/GemTalk/JadeiteForPharo/commit/34f0900d836b2a8d0ae6eab2563b786aa5bc086a

**Comment by ericwinger** [comment]
Checkin: https://github.com/GemTalk/JadeiteForPharo/commit/8f0a20951016c54488cf0b60046891a638c9cf4f

JadeiteBrowserPresenter>>initializePresenters comment which explains how I finally got browser pane resizing to (kind of) finally work: 
	"in order to get scroll bars to (kind of) work, create a paned layout with 
	project & package list. Then create a nother paned layout with the first
	paned layout + the class list, etc.  Then add the final paned layout to the 
	upper box layout. ... Seems unnecessarily complicated. Would be better if 
	I could just add a resizer between two arbitrary widgets."

**Comment by dalehenrich** [comment]
a slider would be nice in the method browser panes ...
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/aa1ac874-10af-4dad-b83b-86b7bba4dcd3)

**Comment by dalehenrich** [comment]
debugger has the same lack of slider and limited code visibility as method browser

**Comment by ericwinger** [comment]
Added slider to method implementors window https://github.com/GemTalk/JadeiteForPharo/commit/c962595a25976f4154d565f0949e285216cc39cb

**Comment by dalehenrich** [comment]
reopening ... please add the changes browser to the list of windows that need a slider, please.
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/4ff4add2-28b4-4e23-9d84-b1d7d3120e79)
BTW, I really like the look of the changes view ...

commit ids:
```
JadeiteForPharo e94a4bf
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices bb1b4a9
```
