### ISSUE TITLE
changed method in method browsers reverts to original source after save

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#10]
In the picture below note that at bottom of yellow text pane (in a method browser) the string `registryFile pathString` and note that in the changes browser (showing the actual change to the method) the string `registryFile fullName` which is the change I made:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/3b2f0d41-f7fe-402c-b10a-9f069970f9fb)
hmm, when I close the method browser and doing another senders of 'pathString', I end up seeing the same method `registryFile pathString` ... despite the fact that changes browser thinks otherwise ....

This one is an odd one...

**Comment by dalehenrich** [comment]
Okay I think I understand ... according to git, the method that was committed was an instance method (I should have noticed that the method was a NEW method not a CHAGNED method in the changes browser):
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/07688110-46ea-4215-b9b3-db73a23cb8f7)
however the original method was a CLASS method ... so when the method was saved, it was saved as an instance method, not a class method and that explains the issue ... apparently the method browser isn't keeping track instance/class methods?

**Comment by dalehenrich** [comment]
When I edit the methods in the project browser, the instance/class distinction is preserved...

**Comment by ericwinger** [comment]
> When I edit the methods in the project browser, the instance/class distinction is preserved...and the method browser source is updated when I make the change

I'm not quite following. Does that mean this isn't a bug?

**Comment by dalehenrich** [comment]
It means that the bug appears to be only present in the method browser

**Comment by LisaAlmarode** [comment]
I'm trying to save methods in a method browser and the changes keep going away.  Method browsers are not functional, this is a bug and not a nice one.

**Comment by LisaAlmarode** [comment]
Also, after saving a method in a method list browser, if I do implementors, I now have two of them on the list. 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/012ed119-1cef-4d81-9339-47a53999b398)
