### ISSUE TITLE
Filein via GsFileIn produces horrible scary stack if you have an unused method temp

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#102]
Did this in Jadeite: GsFileIn fromServerPath: '/home/lalmarod/SoftwareVersion.gs'
Got this stack:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/dfe25531-b182-45a5-a86b-9a827174e346)

Turns out that I had an unused method temp.  This should be ignored in GsFileIn... or at least be presented better.

**Comment by LisaAlmarode** [comment]
Also, after I close that debugger, I get a second one:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/94baa9a1-2882-44bc-8688-61b90d486f0d)

**Comment by ericwinger** [comment]
The scary stack is because interactions weren't supported. Interactions are now supported with the fixes for https://github.com/GemTalk/JadeiteForPharo/issues/99.
