### ISSUE TITLE
`ShouldNotImplement:#remove:ifAbsent: should not have been implmented in Array`

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#105]
I did an abort after loading a new project from a .stone script and got the attached stack
```
JadeiteForPharo 767930d
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices ef59884
```
[forEric.txt](https://github.com/GemTalk/JadeiteForPharo/files/15017828/forEric.txt)

**Comment by dalehenrich** [comment]
had to logout and re-login to see the loaded project ...

**Comment by dalehenrich** [comment]
FYI ... did a similar operation and did not fail ... so not clear whether this is reproducible or not ... however, sending remove:ifAbsent: to an Array should probably be cleaned up

**Comment by ericwinger** [comment]
Using the stack information in the bug report, found a few spots in the code where the class hierarchy's tree model was being set to an Array instead of an OrderedCollection. 
As the report said, it's not easily reproducible so please reopen if it flares again.
