### ISSUE TITLE
move to package menu item in method browser produces MNU asSymbol

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#106]
specifically `a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'asSymbol'` is produced ... 

Picture of stack since I cannot attach stack because of #107. 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/cb3a73cf-3ae5-4f95-a917-5cfeb3a34e90)

commit ids:
```
JadeiteForPharo 86deecf
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices ef59884
```

**Comment by dalehenrich** [comment]
Screen shot of method browser ... ![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/933f17a4-e0c4-4e47-94da-0786ce06e7a3)

**Comment by ericwinger** [comment]
Looks like it was only broken in the method list browser. 

When we issue a command, we set the command & commandArgs in the service and pass it to the server. However, the wrong class service was getting sent to the server in this case. Therefore, the command was nil.

**Comment by ericwinger** [comment]
See previous comment & commit id for fix details.
