### ISSUE TITLE
'dump stack to file' menu item AND `copy stack menu item` produces MNU for #crlf

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#107]
Since I can't copy the stack,
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/ce1d4e23-a53a-4014-8b0c-0c635c66b092)
Stack attached 
commitids:
```
JadeiteForPharo 86deecf
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices ef59884
```
[stack.txt](https://github.com/GemTalk/JadeiteForPharo/files/15226883/stack.txt)

**Comment by ericwinger** [comment]
This may be a version issue. Both debugger menu items work for me. Here are the commits I just tested: 
```
JadeiteForPharo d588f64
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices fa343fc
```
