### ISSUE TITLE
Jadeite locked up reading an RSR socket

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#112]
Here's a picture of the process browser with the RSR socket waiting on Read:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/2017c6c9-5118-4b59-84a8-feddfaa68f55)
Notice that I had selected multiple categories and that is when the lockup appeared to happen ... and no methods were displayed ... 

I selected all of the categories, because I wasn't able to see all of the methods in the selected class ... so Jadeite may have frozen at that moment ... hard to say ... 

Pharo itself is clearly functional .... I'm keeping that Pharo instance around for further debugging if needed ...

commitids (using a different JfP instance):
```
JadeiteForPharo 712a985
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
```
```

**Comment by ericwinger** [comment]
In the process browser, see 4 #basicIssueCommands:...
 
#refreshCategoryListWithSelection: ... refreshMethodsOn: ... #updateService
JadeiteConnectionLauncher>>#openCommitIdWindow
JadeiteBrowserPresetner>>classSelected: ... #refreshClass:
JadeiteBrowserPresenter>>updatePackage

Looks like we were creating a new commandSemaphore in #basicIssueCommand:session:onCompletion: incorrectly. Should reuse the same semaphore. Need to try initializing the commandSemaphore in the RowanUpdater>>initialize method.

**Comment by dalehenrich** [comment]
![Screenshot from 2024-05-20 14-06-06](https://github.com/GemTalk/JadeiteForPharo/assets/623951/390c9edb-6283-4d77-9c1b-0c2e489cbb3b)

**Comment by ericwinger** [comment]
This may be related to, or a symptom of, https://github.com/GemTalk/RemoteServiceReplication/issues/148

**Comment by ericwinger** [comment]
Closing as I believe it's fixed with a redesign of how commands are serviced. RSR bug fixed.  Needs final review.
