### ISSUE TITLE
would like to be able to see breakpoint step point in methods ala JfD

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#113]
I regularly use Jadeite to tell me the breakpoint that I need to set in a topaz script ... with autocommit on in Jadeite it is not convenient to run scripts that add state to the image ... whereas the topaz scripts I run do a logout/login at start to ensure I've got a know starting point and the script itself does not add persistent state changes ... 

Ideal would be same as JfD ... but if the breakpoint browser displayed the currently set breakpoint that would be acceptable and probably more generally useful ...

**Comment by ericwinger** [comment]
To clarify, you'd like to see the step point number and line number in the method source in JfP ala topaz? 

```
topaz 1> break RowanAnsweringService >> allClassNames
topaz 1> run
RowanAnsweringService new allClassNames
%
a Breakpoint occurred (error 6005), Method breakpoint encountered.
1 RowanAnsweringService >> allClassNames        @1 line 1
topaz 1> 
```

**Comment by dalehenrich** [comment]
No, I'd like to hover over a "breakpoint" in the source code ... like you can in JfD:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/4374416f-d829-41b3-8554-5c439e6812d2)

**Comment by ericwinger** [comment]
Clicking on a step point should show the step point in the status bar now.  (I couldn't get a pop-up indicator to work, but hopefully this will suffice) 
![image](https://github.com/user-attachments/assets/cb7a9778-0384-4ee1-9d33-47004fda033f)

**Comment by dalehenrich** [comment]
looks good!
