### ISSUE TITLE
Menu item for methods that puts CLASS_NAME>>SELECTOR into copy buffer 

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#114]
Whether I am writing notes to myself or email to other people or setting a topaz breakpoint, I often need the CLASS_NAME>>SELECTOR form of a method and just absolutely hate having to copy the CLASS name from one place in the browser and then copy and EDIT the selector from another place in the browser ... a menu item like this would save tons of unnecessary editting ...

**Comment by ericwinger** [comment]
I needed that awhile back, too, so I added a button to copy the selected method's signature to the clipboard. Think it does what you want and is in the current checkout. 

Only downside is that the class side methods don't say '<classname> class>>foo'. I'll fix that and publish. 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/d085d1a6-ba3b-4175-bd76-cb4406e9d2e3)

**Comment by LisaAlmarode** [comment]
This looks very easy to get lost.
