### ISSUE TITLE
Login as unsupported user should get a more understandable error than "RSR Broken Promise"

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#115]
When I logged in as DataCurator, I got an RSR Broken Promise error.  This was not a clear indication that only SystemUser is usable.

**Comment by ericwinger** [comment]
I'll add a temporary, "SystemUser is only supported user" (or something like that) for now.  To add support for DataCurator, we'll need to do a little work as DataCurator can't resolve the rowan services classes. 

At minimum, we shouldn't fail on login with an RsrUnknownClass error. In JfD, we modified `STONReader>>lookupClass:` to retrieve the class from Rowan using the class name. 

To accomplish the same behavior in JfP which uses RSR, it looks like we might be able to subclass `RsrServiceSnapshot>>createInstanceRegisteredIn:` and lookup the class from the class name.

**Comment by ericwinger** [comment]
Attaching stack from RSR error. 
[DataCuratorLoginBugStack.txt](https://github.com/user-attachments/files/15687118/DataCuratorLoginBugStack.txt)

**Comment by ericwinger** [comment]
Nicer error message for non-SystemUser logins: https://github.com/GemTalk/JadeiteForPharo/commit/61fbe703c50a1728e36cd8f1714e408a6e26faff
