### ISSUE TITLE
Need to support DataCurator login

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/JadeiteForPharo#116]
Comments from #115 on one possible way to do this. 

https://github.com/GemTalk/JadeiteForPharo/issues/115#issuecomment-2153495376
https://github.com/GemTalk/JadeiteForPharo/issues/115#issuecomment-2153501394

**Comment by dalehenrich** [comment]
These Rowan issues are involved/required for supporting DataCurator login: GemTalk/Rowan#815, GemTalk/Rowan#686, GemTalk/Rowan#227, GemTalk/Rowan#244 ...

**Comment by ericwinger** [comment]
Believe this was solved with fixes to RSR issue https://github.com/GemTalk/RemoteServiceReplication/issues/153 and implementing a custom RCS resolver https://github.com/GemTalk/RowanClientServices/commit/93e8d64452f2d8855ee31fb6b7e9e877efefc5e8
