### ISSUE TITLE
When creating a new method in a method browser, on accept the methods source disappears ... 

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#118]
The method shows up in the project browser, but I have been used to being able to edit a method in a method browser and change the selector at will ... 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/27167f6b-7005-42b9-9b12-74c1be0b5bed)
Commit ids:
```
JadeiteForPharo b249fec
PharoGemStoneFFI 3575de4
RemoteServiceReplication 04f33ca
---------------------------------------------
RowanClientServices 037a3db
```

**Comment by ericwinger** [comment]
I believe the newly-created method source will stay visible in the method list browser and can be edited. The new source and subsequent edits appear in the browser, as well. 

It won't show up in the method list as that would be incorrect.
