### ISSUE TITLE
would like to have writeProject (write without commit) menu item sooner rather than later ...

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#12]
This is a medium priority issue for me ... I prefer to save my changes to disk much more frequently than I want to make commits ... especially when I am working on the GsDevKit_stones solo scripts ... most of the script logic is in a package, so just debugging a solo script problem involves making changes in JfP and writing  changes to disk and immediately running the script and right now, I have to make commits on each "write" where I would prefer to be able to do a commit when I am done with fixing an issue ...

**Comment by ericwinger** [comment]
Added Write Project option in project menu option

https://github.com/GemTalk/JadeiteForPharo/commit/6872ef4a6b5e7df32978ddd53b21107b2493ad3e
