### ISSUE TITLE
Need to restore `refresh` menu item functionality from JfD

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#122]
`refresh` reads the project status from disk and refreshes the console display updating SHA and dirty status on disk ... if you ever update a git repo on disk, you need this menu item. It appears the `changes` will refresh the console display as a short term workaround

The current `Refresh from Disk` should be renamed to `reload`  to disambiguate the use of `refresh` ... nice symmetry with the `unload` menu item ...

The current `Load...` should be renamed to `install...` or `install project...`  to disambiguate the use of `load` ...

**Comment by ericwinger** [comment]
Changed the menu options as shown in the picture. Can rename or reorder as requested. 

![image](https://github.com/user-attachments/assets/24e37213-f71b-44d4-b191-0426541ee9cf)

**Comment by LisaAlmarode** [comment]
I'm seeing the refresh is automatic, but the menu item does exist; and I don't see that Load... was renamed to Install..., but I don't feel strongly.
