### ISSUE TITLE
Certain aspects of JfP windows not updated properly when font szes are applied to already open windows

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#123]
The following screen shots were taken while changing the font settings (to a very large size) and and reopening windows in place ... not the clipping in some parts of the windows :

 ![image](https://github.com/user-attachments/assets/5a31fc81-5f25-41b9-86f9-46f82dde6e8b)
![image](https://github.com/user-attachments/assets/862effc1-05f8-4858-ba74-658fa8cc5614)
![image](https://github.com/user-attachments/assets/a006da0a-0898-4a53-9f3b-28d415ba877f)

The code font size WAS not updated when changes were made in the settings window ... 

The following image was created after closing all windws, changing the fonts to reasonable values (for my display) and reopening the windows ...
![image](https://github.com/user-attachments/assets/bb335744-8df9-4406-982b-20c5eacf2641)

The following image was taken after selecting the Medium font setting and reopening all of the windows:
![image](https://github.com/user-attachments/assets/1ca5d91c-052b-475a-b92e-77264257a0be)

The clipping is most sever in the Jadeite connection launcher ...

**Comment by ericwinger** [comment]
Looks like Pharo has similar problems. Look what happened to the Settings browser when I made the font very large.

To fix this, each widget on each tool would have to be examined for constraints limiting the width and height, especially the latter. Although, dynamic update may not be well supported anyway. 

![image](https://github.com/user-attachments/assets/5def54af-5c4d-46ff-99d4-d8ecc3b2d43d)

**Comment by ericwinger** [comment]
I made a pass at this and fixed a number of spots in the tools where I could see text being cutoff. The connection launcher required the most changes. The initial window size of tools now change based on the point size of the default font. 

![image](https://github.com/user-attachments/assets/8e2e85d0-fe65-4cb5-bf09-312f0d4f6cdf)
![image](https://github.com/user-attachments/assets/1c2f9af7-c943-4b8f-906d-90770c907ce3)
