### ISSUE TITLE
Commit failures may not be handled well with autocommit on

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/JadeiteForPharo#124]
Verify that this is (or isn't) a problem in Jadeite for Pharo.

https://github.com/GemTalk/Jadeite/issues/1010

**Comment by ericwinger** [comment]
There weren't any recursions that I found for an autocommit failure.  I did fix one place which didn't seem to be getting autocommit failure notifications - workspace. Closing. Can reopen if we find a specific failure case.

**Comment by LisaAlmarode** [comment]
A simple case did put up a warning (with details not very understandable, but that's commit conflicts for you). Post-dialog behavior needs work, see issue #249
