### ISSUE TITLE
MNU #do: during updateMethodSource [commit 7a7c08044a01de25a8e1a01ada39dad32f020166]

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#13]
Getting this error despite fact that I have "closed all browsers":
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/29f9b513-8c02-4261-aa3c-47c144793a24)

**Comment by dalehenrich** [comment]
Occurs after doing a refresh from disk with no windows visible ...

**Comment by dalehenrich** [comment]
reopening Console seems to clear it up ...

**Comment by ericwinger** [comment]
Will have a possible fix in https://github.com/GemTalk/JadeiteForPharo/commit/69f4e36e39c5dad2496fdd87b887679da29cf7ee . Need Dale to confirm the fix after it's merged to the main branch since it's not reproduceable.

**Comment by dalehenrich** [comment]
Haven't seen this one lately
