### ISSUE TITLE
First printIt after text entry in workspace puts results at top of pane 

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/JadeiteForPharo#131]
To reproduce: 

- Open a new workspace. 
- type in some text 
- do an adhoc print it. 
- The print it result shows at the top of the screen. 
- Do adhoc print it again. 
- The print it result shows in the expected position. 
- Type in some text and repeat print its.
- First print it goes to the top as before. Next print it is in proper spot. 

Overriding `JadeiteTextDocument class>>#adapterName` to use the super class implementation eliminates the problem. That points to a problem in how our adapter is building the widget. 

First printIt display after typing text (incorrect): 
![image](https://github.com/user-attachments/assets/24c681c7-4397-47e2-b780-1cedfb68c5b4)

All subsequent printIt without typing text (correct): 
![image](https://github.com/user-attachments/assets/931ed17b-0dd5-4e5e-a3fd-4bcf31fe2f4f)

**Comment by LisaAlmarode** [comment]
I think this was reported only for print its using the keyboard shortcuts, not the mouse.  It appears not to be a problem now, but see related issue #201/#219.
