### ISSUE TITLE
debug-it does not always stop at first breakpoint

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/JadeiteForPharo#132]
'Debug it' in a text pane should open a debugger at the beginning of the ad-hoc execution but does not unless there is another breakpoint set in the image. It's almost as if the server needs a breakpoint to exist in a persisted method before it will honor breakpoints in temporary methods. 

The method that compiles the temporary method and sets the breakpoint is here. And it sets the breakpointLevel to 1 so the breakpoint will be signalled to Smalltalk which is where jadeite is waiting for it via rsr. 
```
RowanAnsweringService>>basicExec:context:shouldDebug:returningString:
```

To reproduce. 

- Remove all breakpoints from all methods. 
- 'Debug it' on 123 in a Jadeite workspace. 
- No debugger opens
- Set a breakpoint in some method on the server. 
- 'Debug it' on 123 in a Jadeite workspace. 
- Debugger opens at the start of execution.

**Comment by ericwinger** [comment]
With tracing code, it appears that in the error condition (no debugger opened) the breakpoint does not reach the debug action block.

**Comment by LisaAlmarode** [comment]
The effect of this bug is that debug-it is a no-op.

**Comment by ericwinger** [comment]
In a pinch, we could revert to putting "self halt" in the code manually. Would like to understand the behavior first though.

**Comment by ericwinger** [comment]
Restored the "self halt" debugging code. https://github.com/GemTalk/RowanClientServices/commit/1eb0c966f3736dc5d8aeb132a8f1d1a976414f0b

**Comment by dalehenrich** [comment]
... just in case ... do you have native code disabled ... if you don't have native code disabled breakpoints will not be honored ... native code is enabled by default ...

**Comment by ericwinger** [comment]
Turn off native code by setting a breakpoint in a compiled method first which turns off native code mode and puts it the server in interpreted mode. Then the breakpoint in the debug-it execution will be honored. Unset the secret breakpoint after.
