### ISSUE TITLE
Handle method recompilation after class definition changes

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/JadeiteForPharo#134]
Rowan issue #935 https://github.com/GemTalk/Rowan/issues/935 is a Jadeite error. Jadeite was suppressing the compile error and returning a nil which got Rowan a little confused. 

Need to handle method compile errors when class definition is saved.

**Comment by ericwinger** [comment]
Now we show an error when the method recompilation fails after class compilation and don't complete the latter.

**Comment by LisaAlmarode** [comment]
Handling when method compile errors is quite broken in alpha, but there are exsting and/or will file new issues since nothing more is planned for alpha.  Documented in help.
