### ISSUE TITLE
How to connect to GS via JadeiteForPharo?

### ISSUE THREAD

**Issue by tukanos** [GemTalk/JadeiteForPharo#143]
I have tried to connect to GS 3.7.1 using Pharo 12 and JadeiteForPharo.  I have followed the instructions on this project, but it seems to end up in wait loop.

I would like to ask the following questions:

1) Is the Rowan3 requirement for GS or Pharo or both?  I have Rowan3 extent on GS, but not in Pharo.  In case it was meant for Pharo, how do I load Rowan3 to Pharo12?

2) I tried to debug it and since I have found check in pharo `JadeitePreferences isRowanLoaded`, which gives me idea that the Rowan3 should be loaded in Pharo, but I'm not certain.

3) The connection waits for the `installTranscript` forever:
Here is the walkBack stack:
```Smalltalk
[[self isResolved] whileFalse: [resolvedMutex wait]] in RsrPromise>>waitForResolution in Block: [[self isResolved] whileFalse: [resolvedMutex [..]
FullBlockClosure(BlockClosure)>>ensure:
RsrPromise>>waitForResolution
RsrPromise>>wait
RowanTranscriptServiceClient(RowanTranscriptService)>>installTranscript
JadeiteConsoleWithoutRowan(JadeiteConsole)>>installTranscript
[
		inst := self new: self jadeiteConsoleClass.
		inst
			addStyle: 'jadeiteTextBackgroundColor';
			gciSession: gciSession;
			installTranscript;
			updateProjects;
			initializeAutoCommit.
		self jadeiteConsoleClass currentConsole: inst.
		inst open ] in JadeiteConsoleApplication>>start in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
RowanServiceUpdater>>critical:
JadeiteConsoleApplication>>start
JadeiteConsoleApplication class(JadeiteApplication class)>>showOnSession:
[ :theConnection |
		theConnection
			ifNil: [ self closeWindowsForConnection: lastConnection ]
			ifNotNil: [ JadeiteConsoleApplication showOnSession: theConnection ].
		self enableButtons.
		lastConnection := theConnection ] in JadeiteConnectionLauncher>>connectConnection in Block: [ :theConnection |...
FullBlockClosure(BlockClosure)>>cull:
FullBlockClosure(BlockClosure)>>cull:cull:
[ :block | block cull: self value cull: oldValue ] in ObservableValueHolder>>valueChanged: in Block: [ :block | block cull: self value cull: oldValue ]
OrderedCollection>>do:
ObservableValueHolder>>valueChanged:
[
	lock := true.
	oldValue := value.
	value := anObject.
	self valueChanged: oldValue ] in ObservableValueHolder>>value: in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
ObservableValueHolder>>value:
JadeiteGCIConnectionProfile>>connect
[ self connectionProfile connect ] in JadeiteConnectionLauncher>>connect in Block: [ self connectionProfile connect ]
FullBlockClosure(BlockClosure)>>on:do:
JadeiteConnectionLauncher>>connect
[ self connect ] in JadeiteConnectionLauncher>>initializeButtons in Block: [ self connect ]
SpButtonPresenter>>performAction
SpMorphicButtonAdapter>>action
SpPluggableButtonMorph(PluggableButtonMorph)>>performAction:
[:m |
		(m containsPoint: evt cursorPoint) ifTrue: [m enabled ifTrue: [ m performAction: evt ]]] in SpPluggableButtonMorph(PluggableButtonMorph)>>mouseUp: in Block: [:m |...
Array(SequenceableCollection)>>do:
SpPluggableButtonMorph(PluggableButtonMorph)>>mouseUp:
SpPluggableButtonMorph(Morph)>>handleMouseUp:
MouseButtonEvent>>sentTo:
SpPluggableButtonMorph(Morph)>>handleEvent:
SpPluggableButtonMorph(Morph)>>handleFocusEvent:
[
		result := focusHolder handleFocusEvent: transformedEvent.
	] in HandMorph>>sendFocusEvent:to:clear: in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
[
		(morphicWorld activeHand isNotNil and: [ anEvent hand isNotNil ]) ifTrue: [
			morphicWorld activeHand handleEvent: anEvent
		]
	] in OSWindowMorphicEventHandler>>dispatchMorphicEvent: in Block: [...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycleNow
WorldMorph>>doOneCycle
[
		| extraWorldsToDraw |
		extraWorldsToDraw := ExtraWorldListMutex critical: [
			                     self extraWorldList ].
		extraWorldsToDraw do: [ :world | world doOneCycle ].

		(self currentWorld isNotNil and: [
			 (extraWorldsToDraw includes: self currentWorld) not ]) ifTrue: [
			self currentWorld doOneCycle ] ] in WorldMorph class>>doOneCycle in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
WorldState class>>doDrawCycleWith:
WorldMorph class>>doOneCycle
MorphicRenderLoop>>doOneCycle
MorphicRenderLoop>>doOneCycleWhile:
[ MorphicRenderLoop new doOneCycleWhile: [ true ] ] in MorphicUIManager>>spawnNewProcess in Block: [ MorphicRenderLoop new doOneCycleWhile: [ tru[..]
[self value.
			"IMPORTANT: Do not step over next line of code. See method comments for details"
			Processor terminateRealActive] in FullBlockClosure(BlockClosure)>>newProcess in Block: [self value....
```

**Comment by dalehenrich** [comment]
@tukanos, I am looking into this issue now ... recently we have been making some significant changes in a number of the projects required by JadeiteForPharo and most of our recent testing has focused on 3.7.2 (soon to be released) ...  If you could give me the SHAs that you are using for each of these projects  PharoGemStoneFFI, RemoteServiceReplication, and JadeiteForPharo, I will try to reproduce your issue against 3.7.1.

I will also test JfP with the latest SHAs that I have been successfully using with 3.7.2.

To answer your questions:

1. The Rowan3 requirement is for GemStone only and using $GEMSTONE/bin/extent0.rowan3.dbf should be sufficient.
2. The `JadeitePreferences isRowanLoaded` preference is referring to GemStone only ... one of the things that we are currently working is to allow JfP to be used against a GemStone image that does not have Rowan installed (i.e., extent0.dbf, or extent0.seaside.dbf) and that preference is used to reconfigure the browsers and menu items to remove the Rowan specific project tabs and menu items from ProjectBrowser.
3. The `installTranscript` message is one of the methods that can fail when there are mismatches between the server-side and client-side code ...

My goal will be to tag the JfP projects with a `3.7.1` tag that is know to work for GemStone 3.7.1.

**Comment by dalehenrich** [comment]
For 3.7.1, you will need to use Pharo 11 and the following SHAs for each of the projects ... :
```
JadeiteForPharo eaad809
PharoGemStoneFFI 3575de4
RemoteServiceReplication 069b6b8
---------------------------------------------
```
The above SHAs represents the state of each of the above projects on the release date of 3.7.1 and you get a clean load and login for 3.7.1. 

When @ericwinger gets a chance he will finetune the SHAs for 3.7.1 as I am not familiar with the point at which point 3.7.2 was required.

**Comment by tukanos** [comment]
I've even shutdown the GemStone to see if I get an error message from Pharo (to see if at least it is trying):

![Screenshot From 2024-11-04 12-09-43](https://github.com/user-attachments/assets/7870386b-08fb-4843-98b3-40f107ec0d4d)

**Comment by dalehenrich** [comment]
@tukanos I am not quite sure what problem(s?) you are having ... you seem to have verified that you can log into a 3.7.0 stone using JadeiteForPharo? 

The "fishy" SHA is only "fishy" (deprecated) relative to current development against 3.7.2.

I'm not sure what you did to get the stack? Also I cannot zoom into the screen shots that you've sent, so whatever details I'm meant to see I'm not able to see ... 

You mention `Jadaite's 3.7.0 GCI`, but Jadeite is not intended to be used with 3.7.0 ... Rowan 3 isn't available in 3.7.0 and Jadeite is only meant to work with Rowan 3 ($GEMSTONE/bin/extent0.rowan3.dbf)

To understand what is going on I need to more detail about what you are doing ... So Let's focus on the only the error condition (stack(?) that you are seeing) ... 

So we need to know:
1. What version of Pharo you are using?
2. The `Jadeite Git Commit Ids` from the Jadeite Connection Launcher (`About>>Git Commit Ids` menu item)
3. The contents of $GEMSTONE/externals.sha.txt for the stone that you are running ...
4. Confirmation that you are using $GEMSTONE/bin/extent0.rowan3.dbf for the stone that you are connecting to
5. A screen shot of just the JadeiteConnection Launcher (so I can read the entries you are using to login)
6. An overview screen shot of the error stack for conext
7. A text copy of the Pharo stack 

This should give us enough information to diagnose your issue ...

**Comment by ericwinger** [comment]
Hi tukanos, 

Although I haven't looked at all the details you sent, I just noticed that you're logging in as DataCurator. That's not going to work for any version of Jadeite for Pharo except the very latest.  Have you tried logging in as SystemUser? 

Eric

**Comment by tukanos** [comment]
> Hi tukanos,
> 
> Although I haven't looked at all the details you sent, I just noticed that you're logging in as DataCurator. That's not going to work for any version of Jadeite for Pharo except the very latest. Have you tried logging in as SystemUser?
> 
> Eric

Hi Eric,

Now that a key comment.  It did not occur to me that `DataCurator` would not work so I did not try to use different user.   I'm happy to report that with `SystemUser` it indeed works.

Thank you both for your support!

**Comment by ericwinger** [comment]
That's great news!  The problem with the DataCurator login is that the RowanClientServices classes aren't in the symbol list of that user. So, we've had to make some modifications to allow logins which does seem to be working in the latest JfP.

**Comment by tukanos** [comment]
> ...The problem with the DataCurator login is that the RowanClientServices classes aren't in the symbol list of that user....

I see.  How did you get around that issue?  My wild guess, would be to have a default list of classes that would load for every user?

**Comment by ericwinger** [comment]
When RSR resolves the classes in GemStone, Rowan Client Services uses a custom resolver to look up the classes by name in a method that references the classes. Because the methods visibility is determined at compile time, DataCurator can "see" them.
