### ISSUE TITLE
Browsing methods has issues

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#15]
While selecting methods and checking class and instance (and also sometimes selecting the Variable tab by accident), I am seeing weird behavior in the project browser.  

(1) sometimes there are blank lines within the list of categories.  And there are sometimes blank lines in the lists of methods. 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/1cc205c3-19e4-43d9-91bd-9d4da1e8e6ef)

(2) there are not infrequent halt: walkbacks. This may be the result of having the "Variable" tab selected rather than "Category", since I keep clicking on that as it's the right location for class methods. I think I've seen it other times, though.

I don't see a way to get a stack, but here's a picture:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/ccc874ea-a696-4e5c-bc8a-db9b281500e7)

**Comment by ericwinger** [comment]
The first issue should be fixed with the commit #978c253.

**Comment by ericwinger** [comment]
There was a patch put in place recently which should fix the second issue. 

https://github.com/GemTalk/JadeiteForPharo/blame/12720953938ba7b3bb1672d96b5f0c0f755d8d41/RowanClientServicesClient/RowanServiceUpdater.class.st#L410
