### ISSUE TITLE
Browser test running should be serial

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/JadeiteForPharo#152]
@dalehenrich noticed that running tests in the SUnit browser runs them serially.  However, running multiple tests in the code browser does not necessarily run them serially. Tests should run one unit test to completion before running the next test. 

Only run one test at a time from the browser.

**Comment by ericwinger** [comment]
Fixed per commit comments:
```
Now control server calls with the RowanServiceUpdater>>critical: block. 
With that change, need to fork the test running process to ensure Transcript writes and debuggers work aren't blocked by lack of morphic thread access.
```

**Comment by LisaAlmarode** [comment]
On my non-local connection, by clicking quickly between tests that have a sleep in the middle, cause overlap in text execution in both the SUnit and Project browsers.  This is an extreme case, though.
