### ISSUE TITLE
[jfpWor] All JfP windows closed without a promprt 

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#155]
Firstly, I've noticed that in JfP: 
```
JadeiteForPharo 3a9864b
PharoGemStoneFFI 3575de4
RemoteServiceReplication 9a3398d
---------------------------------------------
RowanClientServices e569f2a
```
If you click with the right button outside of a window you get this prompt for every(?) Jadeite Window:
 ![image](https://github.com/user-attachments/assets/8a909de5-ad60-4940-800a-d6153a5d8c6f)
and after clicking all of the No buttons, you get this:
![image](https://github.com/user-attachments/assets/fc803bf9-28ae-442b-8cb7-ad4aab65ff8a)

Just now in JfP with Rowan3Stub loaded:
```
JadeiteForPharo cbc3fc0
PharoGemStoneFFI 3575de4
RemoteServiceReplication 9a3398d
---------------------------------------------
Rowan3Stub f766fca
```
I clicked the left button (I think) and it may have been over a window or not with the result that all of my windows were closed without a prompt ... not sure if this is easily reproducible...

**Comment by ericwinger** [comment]
To get multiple prompts to close JfP, 

- Close the console by pressing X - see first Question "Really close window? ..." 
- Right mouse in the background of Pharo image (not on any window) 
- See new Question "Really close window? ..." 
- Lather. Rinse. Repeat.

![image](https://github.com/user-attachments/assets/37bfb3cc-ed40-401e-a7e8-9ca1e12e1730)

**Comment by ericwinger** [comment]
Actually, the confirmation problem is anytime you try to open up the world context menu.  Pharo asks every non collapsed window if it `canDiscardEdits` so it can color menu items without considering that some windows want to ask the user for input.  Adding `JadeiteGlobalWindowPresenter>>#okToChange` to perform the confirmation and removing `JadeiteGlobalWindowPresenter>>#canDiscardEdits` should fix the problem.

**Comment by ericwinger** [comment]
The commit fixed the dialog problem. However, there is a question as to whether the second problem (lose all work) is related to the errant dialogs. Since it's not possible to reproduce, going to close the bug with the fix in question and we can open a new issue if the lose all work problem reappears.
