### ISSUE TITLE
[jfpwor] find class doesn't, when done in freshly opened browser

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#156]
In battery_j stone ... (note that partway through this bug report I ended up using a browser that has JadediteForPharo:dkh_monticello [4b70d66] loaded ... the initial report applies and the duplicate class categories are issues) :
```
JadeiteForPharo b4d0ff1
PharoGemStoneFFI 78f7581
RemoteServiceReplication 9a3398d
```
In freshly opened browser, wait for dictionaries and classes to be listed then do a `Find Class` on `Rowan3MCPackageBrowser` and nothing will be displayed:
![image](https://github.com/user-attachments/assets/6d00cd2d-c2fe-41b0-9b13-720fccccc019)
In a freshly opened browser navigate to a class:
![image](https://github.com/user-attachments/assets/98130b32-7cf7-4861-a343-5b10f63a1300)
then `Find Class` on `Rowan3MCPackageBrowser` and you get the following display:
![image](https://github.com/user-attachments/assets/21174491-b33d-4a5b-8e93-94d2cbc0cca4)
... but if you scroll down, in the class category pane, you'll see that the correct class category is selected (Rowan-Monticello-PackageBrowser), however the class itself is not selected:
![image](https://github.com/user-attachments/assets/cbd91b37-88a3-4697-b3f1-cf40eaa58ab3)
The other interesting anomaly here (and possibly the key to the issue)  is that it seems that Jadeite thinks the class is in two categories (Rowan-Monticello-PackageBrowser and Rowan3Stub-Monticello-PackageBrowser):
![image](https://github.com/user-attachments/assets/105fcfde-2483-438e-9320-7b80c96d2c76)
![image](https://github.com/user-attachments/assets/de3e264d-bd43-489b-8970-a4924996247d)

While the class is actually in only the Rowan3Stub-Monticello-PackageBrowser package (which matches the category of the class):
![image](https://github.com/user-attachments/assets/6096891e-5e31-4445-9ea6-8348230e4e10)

**Comment by ericwinger** [comment]
There was a double update of the same class service within a completion block which is forbidden.
