### ISSUE TITLE
Coud use a 'Refresh from disk' menu item on the project browser project menu...

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#16]
... at your leisure currently loaded SHA: 8a4344dabba38b1202e3c4a5e7ab3b4b6c3d3345}

**Comment by ericwinger** [comment]
Think that is already there. Latest main - `978c253` 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/ccdfa023-9f5e-4097-851e-edc835f0a349)

**Comment by ericwinger** [comment]
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/3959cdf0-d329-4771-be13-0b4fea1b55d3)

**Comment by dalehenrich** [comment]
The `Load...` menu is equivalent to the  `Load...` menu item on the project console and that brings up the spec browser. What I want is the `Refresh from disk` functionality from the project console in the project browser

**Comment by ericwinger** [comment]
It's the same menu, so I guess I'm confused. Refresh from disk is the last menu item in the list.
