### ISSUE TITLE
Closing debugger after MNU on inspect it, results in #first was sent to nil and Big Red X

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#17]
I highlighted some text (in a method comment and did an inspect-it, but didn't include highlighting the final character.  See a DNU as you would expect, Use upper right x to close debugger.  This was not expected:

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/de6274dd-62ff-425b-859c-981e758a160b)

This reproduces when doing inspect-in on String foo in a workspace.

**Comment by ericwinger** [comment]
If we got an error during an ad-hoc inspection and terminated the execution, Jadeite  foolishly tried to open the inspector. Now, we look at the service's oop before trying to show the inspector window and make sure we have a valid oop.
