### ISSUE TITLE
Can't code with smart quotes

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#19]
Typing in a single or double quote ' " gives me a smart single or double quote, that is, ´ ¨. This does not work very well to create strings or delimit comments and you can't write code like this.  Possibly this is adjustable somewhere in pharo but it needs to be found and Dealt With. 

I also don't like that the end button brings me to the end of the method, not the end of the line of text, unlike every other application I use.  But this might be a mac or linux thing.

**Comment by LisaAlmarode** [comment]
This appears to be a problem with X2Go; filed internal infrastructure bug 50741.

**Comment by LisaAlmarode** [comment]
Actually a problem with the United States-International keyboard exhibits with both X2Go and TigerVNC, although not on any actual windows apps.

**Comment by ericwinger** [comment]
Going to reopen this to refix the `end` key annoyance.  Pharo has code which specifically looks for `Character cr` when searching for the end of a paragraph. It seemed a good idea at the time, to just display Jadeite source panes in Character cr then convert sources to use lf's on save. Things just worked including the end key. 

However, Dale noticed that copying a method from JfP to a vim editor on linux would have cr's which is not desirable. 

Need a better solution. Coded up a partial solution but I'm not happy with it. 

See these methods for start of re-implementation: 
```
JadeiteMorphicCodeAdapter>>addKeyBindingsTo: 
JadeiteSmalltalkEditor>>#atEndOfLineInsertAndSelect:
JadeiteSmalltalkEditor>>#encompassJadeiteParagraph:
```

The offending Pharo method is 
```
String>>#encompassParagraph: anInterval
	"Return an interval that includes anInterval, and that comprises one or several whole paragraphs in the receiver.
	Answer starts at the position following a cr (or eventually 1) and ends at a cr (or eventually at self size).
	See also #encompassLine:"
	| left right |
	left := (self lastIndexOf: Character cr startingAt: anInterval first - 1 ifAbsent:[0]) + 1.
	right := (self indexOf: Character cr startingAt: (anInterval last max: anInterval first) ifAbsent: [self size]).
	^left to: right
```
