### ISSUE TITLE
Doing "code search" in the code pane of the changes browser searches in Pharo not GemStone

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#2]
Probably on your todo list ... but I'll just report 'em as I see 'em ...

**Comment by ericwinger** [comment]
Try selecting the entire word in the message (don't just put the cursor there) and see if you get GemStone results.

**Comment by dalehenrich** [comment]
Here's a screenshot with a method browser of the results of "implementors of" and a a code browser with `gemstonePath` highligted and getting an empty result.

![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/cb200e5d-1f2d-40e1-af39-364d6ae1c435)

**Comment by ericwinger** [comment]
The changes browser uses a DiffMorph (via the SpDiffPresenter) to display the differences pane which doesn't lend itself to easily override the context menu or slip in a Jadeite text pane.  Probably easier & not as brittle to rewrite the lower part of the changes browser.

**Comment by ericwinger** [comment]
I'm going to call this fixed for now.  Instead of rewriting the changes browser, I hooked into Morphic to do GemStone searches for implementors, senders, etc. (That was not easy) This left in place the difference display which was better than some of the alternatives I looked at.
