### ISSUE TITLE
Could us an autocommit status indication in Console

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#20]
... at least until we have properties files where I can set autocommit on ... I aborted my image and when I looked at diffs I was confused for a few minutes until I figured out that my abort cleared some of the changes that I had already written to disk several days ago without realizing that auto commit was off ... I didn't lose any work, but being able to turn on/off autocommit and see status from Console would be useful ... 

current JfP SHA: 8a4344dabba38b1202e3c4a5e7ab3b4b6c3d3345

**Comment by ericwinger** [comment]
Should have an autocommit button on the console now.  Both browser & console autocommit buttons refresh their color immediately now. Before redraw wouldn't happen until mouse moved.
