### ISSUE TITLE
loading a new project externally and then aborting ends up with new project at bottom of console

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#21]
I loaded (using installProject.stone script) BatteryTest project and it shows up at end of project list ... 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/e90a438d-f1dd-4d82-9d08-2f5e0ad4e7c1)

current JfP SHA: 8a4344dabba38b1202e3c4a5e7ab3b4b6c3d3345

**Comment by ericwinger** [comment]
Projects need to ensure they are sorted during an update. Verified fix using superdoit script `installProject.stone` and unit test.
