### ISSUE TITLE
Saving methods changes in debugger does not save the methods to the class normally

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#22]
One does like to edit code and save from a debugger, but these changes are not retained.

**Comment by ericwinger** [comment]
Believe that this is fixed in 
https://github.com/GemTalk/JadeiteForPharo/commit/e9a4098dab021258d2572c9030c0d2cfa5056365
Requires this commit of RowanClientServices or later. 
https://github.com/GemTalk/RowanClientServices/commit/ff335758dc3341bc79455118d3d4c89d35de05b5
