### ISSUE TITLE
Selected category pane wrong if no category selected

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#24]
When you select a class, by default no method category is selected, but the yellow pane above the method list gets set to one of the method categories, not usually the first one - no customer-visible logic.

If you select a category, this pane is updated correctly. But then if you unselect it (no category selected), it reverts to displaying this default category name, although I think the methods in the list are correct (it shows all methods).  

Marking this as a P3 since it baffled me as I was trying to find a method that tends to hide.

**Comment by ericwinger** [comment]
When selecting classes, if method was selected try to find selector in new class''s method list. If not found, don't select any methods.

**Comment by LisaAlmarode** [comment]
Reopening.... behavior is a bit wonky.  

If I select a new category, the pan should update to show the category, rather than staying blank, and sometimes it shows just "Category:"  Tests are changing categories and unselecting methods and changing categories and so on. 
It's also not reliably showing the template when a category is selected. 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/5f8ad846-0eef-43c7-8108-539efda746b3)
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/bd953545-ae31-4d45-a807-0a820fdcc8b7)

**Comment by ericwinger** [comment]
Behavior should be more consistent now per commit comment. Needs review.

**Comment by LisaAlmarode** [comment]
New issue: when I first select a class, such that no category is selected, the list of methods is displayed, but it doesn't have a scrollbar.  I have to actually select a category to be able to see the methods past the first 10 or so. This is actually very annoying.

Another issue: if you have no categories selected, and you select a method, you can see its category. If you select that category, funny things happen - you may lose the method selection. Sometimes an unrelated method is selected.

Annoying: when you select a class, the categories list is repainted two or three times, with a quite visible flicker.

Previous complaints look fine.

**Comment by ericwinger** [comment]
```
New issue: when I first select a class, such that no category is selected, the list of methods is displayed, but it doesn't have a scrollbar. I have to actually select a category to be able to see the methods past the first 10 or so. This is actually very annoying.
```
This should be fixed in this commit. 
https://github.com/GemTalk/JadeiteForPharo/commit/842840e66b531f81aefdad0bc5ba749b8ff35f68

**Comment by ericwinger** [comment]
```
Annoying: when you select a class, the categories list is repainted two or three times, with a quite visible flicker.
```
Should be fixed: https://github.com/GemTalk/JadeiteForPharo/commit/65d1ed9bdbf67f281e65483cbf39c8c164c7c1a4

**Comment by ericwinger** [comment]
```
Another issue: if you have no categories selected, and you select a method, you can see its category. If you select that category, funny things happen - you may lose the method selection. Sometimes an unrelated method is selected.
```
I *think* this is better as of https://github.com/GemTalk/JadeiteForPharo/commit/debdd5cabe54ddc72a4e7533c783d7ea34f86c45

**Comment by ericwinger** [comment]
Found another bug in category selection which selected the wrong method by default. Made the method selection seem random. 

https://github.com/GemTalk/JadeiteForPharo/commit/44873e7f4d7f78def45279d694db650ba8e9e7a7
