### ISSUE TITLE
String inspector pane issues

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#25]
When you inspect a string, you generally want to be able to see and read the whole string. Alas for the default pane widths in the inspector.

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/b5bb0ec7-deee-48ab-9eca-03af8056d53e)

- [x] having a wide space to show the numeric indexes of the characters and a narrow space for the string is very annoying
- [x] these panes cannot be resized.

- [x] Also, when trying to copy the string to real editor, I had a little menu trouble since it was thinking the contents must be a selector...
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/7374a9f6-f119-4b0a-aa76-781d79c361be)

Given a 500k string, I think the right pane is showing 100k of the text, the numbers on the left only go to 1000. This is not really correct, but this area is a can of worms and should be a separate issue, and 100k of text is enough for me to be happy (until I need to see specific character value after the first 1000 chars...) so I think we can ignore it until it really comes up. 

As a side note, the same weirdly narrow left side is in the dictionary browser, although it's not as obviously wrong since you could have a large key:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/52bd864b-6fca-4387-a175-cbaa3feb8a93)

**Comment by ericwinger** [comment]
Fixed per commit comments
