### ISSUE TITLE
Netldi not running - error message a little overzealous

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#27]
This error message bothers me.  It felt unfair when all that happened was the netldi not running.

Basically it's too wide; I think it's the width that's the problem. Line breaks would be ideal, but failing that (since it comes from the server without), just limiting the width of the dialog might be a reasonable solution.

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/4a027850-41c7-42cd-a6c3-0a655c30d211)

**Comment by ericwinger** [comment]
In GBS, we open a debugger but with the same message. See picture. FWIW

If I width, say 100, it might cut the message at a weird point. Is that better than an overly wide dialog? 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/b169b1e2-d090-489d-ad3a-66a6d729c182)

**Comment by dalehenrich** [comment]
Just riffing, but workspace and source panes do linewrap, so perhaps using one of those would do the trick?
