### ISSUE TITLE
method and category pane not updating after creating a new class

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#28]
In the image below, the selected class GDKScriptNewExtent was just created (with no methods), but after clicking on a class that does have methods and then back to GDKScriptNewExtent, the category and method list are "inherited from the previous class" ... as if since the category and method are empty ther is no reason to draw simething in those panes:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/00b74216-e261-44e3-a2b6-af98921978a0)
 similar thing happens if I click back and forth between category and variable ... the list of variable names is not cleared:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/cd1e01dc-da9e-4241-b419-ef07dc55e9d3)
Here's the project list with SHAS:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/4202b621-e1ed-42de-b95d-5620fb03f19d)

**Comment by dalehenrich** [comment]
Just updated JfP this morning:
```
bosch:JadeiteForPharo>git log -3
commit 892d0fd541715b35f284e72f18999760da94c05f (HEAD -> main, origin/main, origin/eric, origin/HEAD)
Author: Eric Winger <eric.winger@gemtalksystems.com>
Date:   Thu Aug 10 16:09:15 2023 -0700

    Previous fix was incomplete. When testing for package selection, account for gui still building.

```

**Comment by dalehenrich** [comment]
... workaround is to close the project browser, navigate to the class and then add a category ...

**Comment by ericwinger** [comment]
I think that the method and filter panes update properly (for some definition of properly) when a new class is created. Also, when clicking away and back to a class does not "save" method lists.
