### ISSUE TITLE
Need a report to show what all git repository shas I have loaded

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#29]
JadeiteForPharo (and RSR and another git repository) are loaded from Pharo tools, and it's quite difficult to find the loaded sha.
RowanClientServices (and Rowan and a whole bunch of others) are loaded from Jadeite, and are easy to find the sha.

It would be very helpful to have a way to print the shas of both in one place. 

I'm marking this as a P3 since while it's properly an feature, it's making it difficult for me to work (the work being report errors...)

**Comment by dalehenrich** [comment]
Just riffing, but in Pharo it should be straight forward to query the system about the pharo-specific projects and include them in the project browser ... could even report skew and do loads ... if we wanted to ...
