### ISSUE TITLE
After committing a project to disk, I get a warning about loading project and losing changes?

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#3]
missed chance to do screen shot, but was surprised to see that message ... I said "no" and the project appears to be fine... oops the GsDevKit project was dirty and now is not and the sha has not been updated ... which I would expect ... when I selected the refresh menu item I got the notifier (and snapshotted him):
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/68c06101-e5d8-40e9-9784-cd00d4db4341)
I assume you are updating behind the scenes, but somewhere along the way there is an assumption made that the project is being loaded?

**Comment by ericwinger** [comment]
Does this happen when you've got ROWAN_PROJECTS_HOME defined correctly?   (per some slack traffic about ()'d project names)

**Comment by dalehenrich** [comment]
I did it just now and got exactly the same dialog box ... and ROWAN_PROJECTS_HOME is defined ... the subtlety might be that this time the project wasn't dirty in JfP and it was uncommitted on disk
