### ISSUE TITLE
MNU saving a method (SHA[4cae8d064])

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#30]
The initial error occurred when I saved this as a new method ... subsequent attempts to save the method led to the attached stack.
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/71584660-ad9e-41a7-8d65-aaa093d2987f)

[stack.txt](https://github.com/GemTalk/JadeiteForPharo/files/13285035/stack.txt)

**Comment by ericwinger** [comment]
Believe this is fixed per the commit comment.  After saving a method the browser was trying to update selected methods but was only looking at the class list tab for guidance.
