### ISSUE TITLE
Misspell a class name or class variable, get floating yellow error, lose new method contents

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#33]
This floating yellow box appears on both instance and class side, say if you misspell a class name.  It's terrible since the insert is before the not understood symbol, blocking it so I can't actually see what it was that was typed wrong. 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/f8a79df9-47ff-43af-af20-a214371f3a99)

The real problem is that if this is a new method.... you also lose the method contents, it reverts to the template. 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/43f76c80-45be-4e99-a009-95dfafcb388c)

**Comment by ericwinger** [comment]
```
The real problem is that if this is a new method.... you also lose the method contents, it reverts to the template.
```
If you hit backspace or escape, you shouldn't lose the method contents. At least that's what I see when I get a compile error on a new  method. 

I agree, though, that the compile error does obscure the problem.

**Comment by ericwinger** [comment]
Fixed per commit comments. Replicate compile error reporting to match Pharo's which doesn't obscure text.
