### ISSUE TITLE
Save in debugger when in a block context gets walkback

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#34]
Not exactly a surprise, but what I wanted, either.  I hadn't noticed I was in a block context and saved a minor change.  It's not like I expected the saved method to even be actually saved...

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/83baabf9-0d8f-4f40-b70b-ebfe42222a8c)

**Comment by ericwinger** [comment]
I believe this is improved now. Required commits:

-  Rowan Client Services  https://github.com/GemTalk/RowanClientServices/commit/8f34db1cd16af4c9f535df7d09e203bdf3fab6e8
- Jadeite for Pharo https://github.com/GemTalk/JadeiteForPharo/commit/8e7f57c9999b8936bfff860d6610d255455678c8
