### ISSUE TITLE
Workspace 'Print it' does not actual print characters into the workspace

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#37]
Doing a print it in a workspace (such as String new or 3 + 5) produces a display of the result into a transient floating yellow box, which disappears when you click in the workspace.  Actual printing needed.

**Comment by LisaAlmarode** [comment]
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/9ed75473-3bd8-44d1-abbd-2bb215ea4316)

**Comment by LisaAlmarode** [comment]
While I don't like the pharo behavior, the jadeite behavior also does not match pharo; pharo wraps output in double quotes, leaving the contents looking like the original, while jadeite does an additional conversion to string and then wraps it in single quotes and then in double quotes.  So 3+5 prints as "'8'" rather than "8", and ' Say it isn''t so ' prints as "''' Say it isn''''t so '''".

**Comment by ericwinger** [comment]
I'm going to mark this fixed for review.
