### ISSUE TITLE
I'm confused by "refresh" ... I want to reload/load the project from disk ... refresh does not sound like I'm going to get a load

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#4]
Could be related to to the confusion mentioned in  the previous bug?
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/f77a7cdf-284e-495d-ab30-b8f8a41aea82)
If it thinks that the project matches what's on disk (and I know that it does not ... the sha does not match the sha of the previous commit) then that explains my confusion as well :)

**Comment by ericwinger** [comment]
The idea of Refresh was to get a fresh state of the projects from the server. However, I agree that having both Refresh from Disk and Refresh on the menu is confusing.  It would be best if this window always showed you the latest state of the projects. Then I can rename the "Refresh from Disk" to "Reload from Disk"

**Comment by ericwinger** [comment]
To make things easier, I just removed the Refresh project menu option. We can add menu items as the need arises.
