### ISSUE TITLE
Need select all on string inspector popup menu

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#40]
The string inspector popup does not include Select All.  control-A works as a shortcut, anyway, so it should be easy to include on the menu.

**Comment by ericwinger** [comment]
I added Select All in the left pane of the inspector. It was actually requested on the right pane of the inspector.  (Picture is what Ctrl-A does today. Just need it on a pop-up menu)

![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/b8176801-a392-4d90-9c88-124ba0e5b754)

**Comment by LisaAlmarode** [comment]
the left side popup menu looks like this: 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/9e48f31f-3179-4e76-8dd5-a1b56f6f78b7)

It looks sad. The following changes are needed:
- [ ] select all should have the control A shortcut 
- [ ] inspect should have the control I shortcut 
- [ ] the back menu item is missing, which is a pair with dive.  There are icon bar items for both back and dive.
