### ISSUE TITLE
While editing a method, can click on other methods, but method text pane not updated

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#44]
I was editing a method and decided I didn't want to keep my changes. I have always just clicked to another method and back.  
This doesn't work: I am trapped viewing my method source.  It will go away if I select another class, though.

This was more disconcerting since the pane doesn't change color... so I wasn't entirely sure if it my changes where there or not. I did like the green background clueing me in. The teeny orange corner is not enough.

**Comment by ericwinger** [comment]
I'll work on improving the code that asks the user if they want to keep changes when changing methods with unsaved changes present in the source pane. 

FWIW - Hitting the Cancel menu option will restore the original method source. Last popup menu item in the picture. Using a Cancel button seems to be closer to the Pharo way. 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/2cb11aec-55bd-4616-93f4-2f1cbc276991)

**Comment by LisaAlmarode** [comment]
I agree we should keep the cancel button to support pharo users :-) (and I did eventually use it). Just don't think we should confuse and baffle regular folks... if nothing else it should not let you select another method if it's going to keep displaying the one being edited.

**Comment by ericwinger** [comment]
Added another checkin here for handling window closing confirmation, too. 
https://github.com/GemTalk/JadeiteForPharo/commit/23dca172d9cc8e5f5e1da40e5bc70a7a43e91414

**Comment by ericwinger** [comment]
This was a rather deep fix so it's possible there are some side effects, but for the most part, it seems that it's working. Selecting a new method will check for edits and prompt for the user to save or discard them. Window closing works the same way.
