### ISSUE TITLE
Messages lacking line breaks

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#45]
I suspect there are a number of messages like this, that are difficult to read since they are so very, very wide.  It's not highly important but this one I did have to read to the end and it was not fun.

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/47ac2316-2f8f-461e-9e59-181d7a86e9da)

**Comment by ericwinger** [comment]
Used Jadeite's `String>>skinnyPrintOn:` to make the string a bit more readable. 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/194683fc-45e7-4b14-a5cd-eaf9e5f003ae)

**Comment by ericwinger** [comment]
Note - Didn't make the skinny print global for dialog messages (yet).  I still believe that there are dialog warnings and confirmations lurking that have their own formatting which should not be disturbed.
