### ISSUE TITLE
Project Browser method pane multiple select would sure be nice

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#46]
I had 10-12 old test methods to delete.  One by one.  Each one requiring confirmation.

**Comment by ericwinger** [comment]
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/5ffec767-ec94-4d11-b694-c612a5c254db)
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/bf327015-1714-4a02-9a03-2781b5a265c9)

Multi-select delete seems to work for me. 

It's possible, that the multi-select color is so faint that you can't see the other selected methods. I've been frustrated by this for awhile.  If that's the case, I can take a deep-dive and try to make the secondary selections more visible.

**Comment by ericwinger** [comment]
Actually, it looks like (in the latest commit), you can add JadeiteTableMorph>>defaultSecondarySelectionColor to be the following. Secondary selections would be the same as the primary list selection. 

```
defaultSecondarySelectionColor
	^ self defaultSelectionColor
```

**Comment by ericwinger** [comment]
Made the multi-selection colors uniform and visible.
