### ISSUE TITLE
Workspace window is (Untitled) ... 

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#5]
... since the window buttons on bottom of screen is used to access non-visible windows, would be nice it were titled by default ...

**Comment by ericwinger** [comment]
Added a title for the workspace. Probably could do more to make Jadeite windows standout on the taskbar.

**Comment by ericwinger** [comment]
If the new icon added in #38d2da6 helps identify Jadeite windows in the taskbar, we can change that to another icon pretty easily. Although I'm not sure how to design a new icon in Pharo yet. 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/e14cca44-142f-460b-a304-462a0776d9d0)
