### ISSUE TITLE
Class Defintion pane has full set of code menu items

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#50]
The popup for the Project Browser text pane, when the ClassDefinition tab is selected, includes code based options such as do it and senders of.  These all get walkbacks.

**Comment by ericwinger** [comment]
Should be fixed in https://github.com/GemTalk/JadeiteForPharo/commit/b301c2262fd4021685d33950a9e6dc8d03b05ddd

**Comment by LisaAlmarode** [comment]
Things seem to work; while not heavily tested it's acceptable for me.
