### ISSUE TITLE
Online help, including About Jadeite

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#51]
Need to have the Help menu item on the Console, with links to the projects and About Jadeite.  Jadeite help would be nice (it explains the markup on projects), but probably needs to be edited for JforP. 

This is the JforD menu:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/34ef6aa8-d499-4708-b8bc-587f35a866e7)

**Comment by ericwinger** [comment]
Four working menu items added: 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/01856092-fc10-4a54-a996-fe7c5e4eecf4)

**Comment by ericwinger** [comment]
Note that jadeitehelp.html and jadeitehelp.css can be changed and committed to git without any changes to Jadeite code as in Jadeite for Dolphin. These files are part of the Jadeite for Pharo checkout and will be copied to the Pharo image directory when the Jadeite for Pharo package is loaded.
