### ISSUE TITLE
Additional git options: git log, checkout git tag, checkout git branch, pull from git

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#52]
JforD provides menu items for git log and checking out a git tag or branch, and pull from git.  These are useful and I've missed them when trying to see what was going on. 

For reference, this is the menu item names and order in JforD.  I think the order in JforD is probably not ideal, at least Git Log should be under Push to Git. IMO.

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/fc0f6fd6-df93-4d48-8dc9-3599f0929f4e)

**Comment by ericwinger** [comment]
Opened bug https://github.com/GemTalk/Rowan/issues/910 for checkout issue. When that is fixed, this can be tested.

**Comment by ericwinger** [comment]
#910 turned out to not be a bug but https://github.com/GemTalk/Rowan/issues/912 does seem to be a legitimate problem. Once that is fixed, can be retested.

**Comment by ericwinger** [comment]
Closing this as I think the missing menu items are in place and working. Would not be a bad idea to test this a little more.
