### ISSUE TITLE
Project Changes revert (and other missing features)

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#54]
- [x] The Project Changes (Console project list popup menu item Changes), does not have revert on the popup menu.  I like this since I tend to add bug reproduction methods that I want to find and remove.  Moderately high importance.

- [x]  The JforD Changes Browser includes a Jadeite menu toggle item, Include Methods With Identical Source. Medium Importance.

- [x]  It also doesn't have the Browse, Browse Implementors and Browse Senders menu items.  Low Importance (to me at least)

**Comment by ericwinger** [comment]
https://github.com/GemTalk/JadeiteForPharo/commit/580e9f4a02dea3623d7b7b3eb0720245532f60c4

@LisaAlmarode Please review and reopen if features added aren't up to snuff.
