### ISSUE TITLE
Request changing the background color on edit/error

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#55]
In JforD, when you start editing a method, the background turns green.  If you save with an error, it turns pink.

I really like these color changes (the green, at least).  The pharo corner color is completely inadequate.  The GBS big red dot on the Source tab is at least right there in your face, where the code is that you are staring at, not way off to the far side of the windows. 

This mentioned in #44 but deserves its own issue.

**Comment by ericwinger** [comment]
Should have the green background working in https://github.com/GemTalk/JadeiteForPharo/commit/c9bd0ba6c9fcc584b2db711500ccc454a1b4a9ad

**Comment by ericwinger** [comment]
Added red dot that shows up if method source, class comment, or class definition panes changed. 

https://github.com/GemTalk/JadeiteForPharo/commit/f006867fe29dadab863b0774c83096bc4b32040e
https://github.com/GemTalk/JadeiteForPharo/commit/919183710b732385e041cd13899918807d98b4a7
