### ISSUE TITLE
Saving a file gets walkback (and doesn't remember its name)

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#57]
If you open a server file (using the Console File men item), trying to save it using Save on Server or Save On Server As... (which are apparently identical anyway) gets a walkback.

Also, Save On Server should save the file with the same name and path, rather than doing a Save On Server As:, and offering to save it as workspace.txt in $ROWAN_PROJECTS_HOME. Both Save on Server or Save On Server As...  should start the file selection dialog in the location of the original file opened.

**Comment by ericwinger** [comment]
Think saving a file should be a little better now.
