### ISSUE TITLE
[JfP:f4dd672] when senders browser is opened on a number methods and edits are being made....

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#63]
.... the order of methods in the list seems to randomly change and "the next method in the list" has already been edited ... makes me wonder if I have skipped methods and am forced to go back and review "already edited" methods to make sure that the edits were made ...
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/0e66552d-fcf2-49cd-9c1e-86ab91cc04e4)

**Comment by dalehenrich** [comment]
It looks like when I save the method, the "selected method" (blue highlight) is switched to an earlier method than the one the edit was made to ... possibly happening when the list needs to scroll ... it seems like the selected method is an index in the visible list instead of an absolute position ... 

as an FYI ... I am editing nearly every one of the 47 methods ... or at least I am hoping that I am ...

**Comment by dalehenrich** [comment]
... yep... now that I'm halfway, the selected method highlight never stays on the current method and I have to hunt for the next method to edit ... but looking to see if the change has already been made ...

**Comment by dalehenrich** [comment]
Here's a case where the method selection disappeared completely leaving me on the edit window ... and the list didn't move ... so I need to hunt for the last method I've modified:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/775b41d5-19ea-43f2-b872-5a1b5bae1359)

**Comment by ericwinger** [comment]
What commit do you have loaded?

**Comment by dalehenrich** [comment]
it's in the title

**Comment by dalehenrich** [comment]
I just noticed that the selection jumped to an earlier with with the same selector but a different class ...

**Comment by dalehenrich** [comment]
I don't know if that is the only mechanism or not ... but i've made 30 edits or so and have ample opportunity to watch things hop around :)

**Comment by dalehenrich** [comment]
Yep it is finding an earlier method with the same selector and a different class ...

**Comment by ericwinger** [comment]
I see it now.
