### ISSUE TITLE
[JfP: 4baac2bc5] Infinite autcommit prompt and MNU for transaction conflicts

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#66]
Selecting yes just pops up the dialog again:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/24c227cb-022f-49da-8b70-42db04e575fb)
Selecting no ends up in debugger:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/537e3d5e-9d6f-4218-bc5d-74f1d4cd1e63)
Not a priority ... I was working in both JfD and JfP at the same time and did some loads in JfD, that I wanted to see in JfP ... I had successfully aborted in JfP at an earlier time to use the cool differences browser :) ... so not sure how I got here ...

I'm done working so I will leave the JfP debugger around in case useful stuff can be gleaned ...

Not a priority for me ... so can just kill and restart JfP if needed ....

**Comment by dalehenrich** [comment]
I just did a fresh login into JfP and right out of the box and when I abort, I get the infinite abort loop ... which is odd

**Comment by dalehenrich** [comment]
... and cannot turn on auto commit ...

**Comment by dalehenrich** [comment]
and immediately after pressing the commit button button, I get the inifinite prompt when I press the abort button ... cannot turn on autocommit either ... I am logged into JfD and it is unaffected ... 

JfP is unhappy after logging out of JfD and logging in fresh ... going to bump the priority on this one ... going without autocommit support is not quite safe ...

**Comment by ericwinger** [comment]
Not sure what the autocommit failure is about but need to make `displayTransactionConflicts:` actually work. The method isn't implemented yet so pressing No from that dialog will fail until I fix it.

**Comment by dalehenrich** [comment]
built a fresh image and the commit issue does not reproduce ... turns out that the Jadeite Launcher was out of date with respect to the "loaded sha"

Closing for now

**Comment by ericwinger** [comment]
I believe at least the original problem is fixed. Also, found what could create the infinite autocommit failure problem although I couldn't reproduce. A client service inst vars didn't match the server but wasn't being reported by RSR. Instead it would silently fail leaving the autoCommit inst var in a bad state.
