### ISSUE TITLE
MNU, when inspecting an object that has it's own issue with printString ...

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#7]
... I think in JfD, errors are caught while generating the printString for inspected objects...

**Comment by ericwinger** [comment]
Could you provide a little more detail on what kind of errors you're seeing?  Here is what JfP tries to do for objects with problematic printString's: 

![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/cea866fb-7d0d-46c7-bf5b-94707689223b)

**Comment by LisaAlmarode** [comment]
It doesn't look like there are problems, so closing, reopen with more details if we're missing something.
