### ISSUE TITLE
red window morhpic death: after running a successful test in SUNIT browser

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#71]
After confirming that Issue #70 was [no longer an issue](https://github.com/GemTalk/JadeiteForPharo/issues/70#issuecomment-1913794765) ... I had left the method browser window open on the method after removing the breakpoint and then reran the SUNIT test expecting a pass (no breakpoints involved) ,, the test passed, but the method browser had a morphic error:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/254bbf8c-dc24-4036-bef5-259e88865e14)
JfP git report:
```
JadeiteForPharo 82dc6f0
PharoGemStoneFFI 3575de4
RemoteServiceReplication f90b9c1
---------------------------------------------
RowanClientServices 5a7a68c
```

**Comment by ericwinger** [comment]
I believe that the reason for these red death windows has been eliminated with a redesign of how JfP uses RSR. No more swapping morphic processes.
