### ISSUE TITLE
reload of JadeiteForPharo with uncommitted changes hits FileExists: jadeitehelp.html error

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#72]
Both jadeitehelp.html and jadeitehelp.css files are present in my Pharo 11 image directory (/home/dhenrich/Pharo/images/Pharo 11.0 - 64bit (rowan3)) and both files cause errors ... Copy stack to clipboard apparently doesn't work so I can't provide a text stack ...
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/e9d09382-78cc-425d-ba5a-f1d4955db13b)

**Comment by ericwinger** [comment]
We now ensure that the local jadeitehelp.css & .html file are removed before copying during the post load. 
https://github.com/GemTalk/JadeiteForPharo/commit/00cecd8b9b0f346dde14d4a562e3cc0f9c5aa5c8
