### ISSUE TITLE
spurious CR show up when copying text from JfP on Linux

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#73]
Here's a picture with the ^M ...
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/cc7f5b20-5cec-424e-bde8-88c280e723c9)
I've already commented out `replaceLfWithCr` in JadeiteTextDocument>>#value: ...  and the odd part here is these guys are showing up in text I had pasted into the method and not saved yet ...

**Comment by dalehenrich** [comment]
... I had to copy the unsaved method, because I ran into issues that could jeopardize the image itself and I didn't wamt to lose the work  ...

**Comment by ericwinger** [comment]
I believe that we should be using Character lf in sources everywhere now, but please reopen if cr's are discovered in source code again.
