### ISSUE TITLE
Class side method dragged to another class ends up on the instance side

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#77]
I dragged RwRepositoryResolvedProjectTonelReaderVisitorV2 class>>lineNumberStringForMethod: to RwRepositoryComponentProjectReaderVisitor and the method ended up on the instance side of the class...
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/8afef155-3285-438f-8ab3-4a2ab11becd9)

I consider drag/drop a convenience ...

**Comment by dalehenrich** [comment]
commit ids:
```
JadeiteForPharo 19b3ae8
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices 6a14a8f
```

**Comment by ericwinger** [comment]
Make sure to set the `meta` variable  correctly when compiling dropped methods.
