### ISSUE TITLE
Closing debugger on test with `halt` ... launched from a workspace doit

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#82]
The first picture shows the workspace and debugger that I got after closing the debugger that had the halt in it and hitting `CTL-.` since the window appeared to be hung ...
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/11e748b5-300d-4bd0-bc36-53585b7014a0)
[stack_1.log](https://github.com/GemTalk/JadeiteForPharo/files/14643764/forEric_1.log)

The second picture shows another debugger that popped up right after I took the first screen shot:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/1ab077e3-ee0f-4576-ad7d-892571db7600)
[stack_2.log](https://github.com/GemTalk/JadeiteForPharo/files/14643765/forEric_2.log)

The stacks look suspiciously short ... but I didn't find a better menu option than copy to clipboard

**Comment by dalehenrich** [comment]
commit ids:
```
JadeiteForPharo 2584dc0
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices bb1b4a9
```

**Comment by ericwinger** [comment]
Looks like the RSR version is not the same. 
```
JadeiteForPharo 2584dc0
PharoGemStoneFFI 3575de4
RemoteServiceReplication f90b9c1
---------------------------------------------
RowanClientServices bb1b4a9
```

**Comment by ericwinger** [comment]
Recently added code to handle the termination of a remote service message did not handle RsrConnectionClosedBeforeReceivingResponse which is strangely not a subclass of Error.
