### ISSUE TITLE
on "refresh" of a project that ends up updating several projects, the required required projects stay red

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#84]
The Cypress and STON should be black in project browser:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/cdcf5025-d8a8-4956-969b-893dfb4b1b0a)
Note that the console was updated correctly ...

**Comment by ericwinger** [comment]
I believe this is fixed in a commit from awhile ago. I retested and it appears to work. There was problem where some code was in an rsr completion block that shouldn't have been.
