### ISSUE TITLE
Would be useful to be able to browse refrences to the class of the method in the method browser ...

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#85]
I thought that this feature already existed so here's the screenshot and this method browser was launched from a "methods containing" menu item:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/cb2201b1-8614-4298-b2bd-1bed216b2782)

Commit Ids:
```
JadeiteForPharo e94a4bf
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices bb1b4a9
```

**Comment by ericwinger** [comment]
I'll add it to the method list browser but in the meantime you can Browse Class form the method list browser, then Browse References from the project browser. 
![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/2b325e51-b904-42a0-a08d-c8f6529cf886)

**Comment by ericwinger** [comment]
Also added class reference method count. 
References is available in a number of different places and seems to work in all of them. 
Improved execution time of browse class refs by about 80%.

![image](https://github.com/GemTalk/JadeiteForPharo/assets/36212516/5a80b6ba-65a8-4095-9cbd-33d9270123e9)
