### ISSUE TITLE
Things disappearing from SUnit browser (test methods and packages)

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#86]
If I have any of the test classes selected in the Project Browser, the SUnit browser shows me none of these classes. 

This is when things are normal:

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/f0063c8b-00e8-4a08-bee1-d82145c73eca)

Then when I select something in the Project Browser (I might have had to click on a different class in the SUnit Browser and back)

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/a16da57a-3eed-48d2-8751-4e6b1eb7c384)

EVEN MORE EXCITING...
go back to the Project Browser and commit (using the icon), 

and many but not all of the packages are no longer displayed...

![image](https://github.com/GemTalk/JadeiteForPharo/assets/13142166/bc1608f7-f3ec-4e1a-8974-c56323509b55)

**Comment by ericwinger** [comment]
We'll want to confirm that the latest code in JfP and RCS is loaded.

**Comment by ericwinger** [comment]
Here are the commit ids I am using: 
```
JadeiteForPharo d588f64
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices fa343fc
```

**Comment by LisaAlmarode** [comment]
Incorrectly closed by workflow

**Comment by ericwinger** [comment]
I believe this has been fixed as I did a lot of work in this area over the last few months. Attempts to reproduce were negative.
