### ISSUE TITLE
Step into after breakpoint encountered hangs pharo

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#87]
If you sent a breakpoint on a selector in a test method,
and you run the test using the Project Browser method pane gray button,
it breaks and brings up an apparently functional debugger.  So far so good.

Using step into to step into the highlighted method, however, causes pharo to hang.  
left-control- period broke the hang but unsurprisingly the image did not return to a useable state.

This reproduces reliably.

**Comment by LisaAlmarode** [comment]
step over and step through have the same problem, but proceed did work.

**Comment by ericwinger** [comment]
Believe this is fixed. Many commits from https://github.com/GemTalk/JadeiteForPharo/commit/951182dc5f36e8ecccd6b2828a2abdb5a7c32c68 to https://github.com/GemTalk/JadeiteForPharo/commit/3de7197e32a2aad09f27902dc4a0cc552f2e2685 are likely needed as there were process handling changes.
