### ISSUE TITLE
class hierarchy calculation in the project browser can be very slow ... 

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#89]
This is not an immediate problem, but at the moment it is noticeably slower that JfD ...

**Comment by ericwinger** [comment]
The hierarchy browser was completely reworked and is much faster. Need feedback. 
For reference, in my image, selecting Object in the class list tab then selecting hierarchy takes about 5 seconds. I would consider this the worst case scenario with most hierarchy lookups being much faster.
