### ISSUE TITLE
Package>>Add Package menu item disabled?

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#9]
When I first opened the browser, the Package>>Add Package menu item was enabled and brought up the dialog and saw that I needed to supply a component name ... once I figured out which component name I wanted to used, the  Package>>Add Package menu item was disabled.

Closing and re-opening the project browser, it seems that the add package menu item is only enabled when no project is selected?

![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/ad23bbad-a6b0-4931-98f9-b04a820cc300)

Not a priority, I just wanted to use it if I could :)

**Comment by ericwinger** [comment]
The conditional logic was backwards. Fixed in the aforementioned commit.
