### ISSUE TITLE
would be convenient to have files listed in selected directory when saving connection file ...

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#91]
I'm finding myself saving these guys pretty regularly ... when the netldi port changes ... and it's annoying to have to retype the name of the file every time I save it ... if you saved the name of the file used when the connection was imported and used that as the default name, then listing the files in the directory would not be necessary ....

**Comment by ericwinger** [comment]
Import connection file name used as default for export connection file name dialog.
