### ISSUE TITLE
Class Hierarchy doesn't display if the "class" radio button is selected.

### ISSUE THREAD

**Issue by JupiterJones** [GemTalk/JadeiteForPharo#92]
When browsing class methods ie. the "class" radio button is selected, and you click the "Hierarchy" tab to view the class hierarchy, it doesn't display. Change back to browsing "instance" methods, and it works again.

**Comment by ericwinger** [comment]
After building the hierarchy, the class was supposed to be selected in the tree but wasn't because the equality test failed. Equality is based, in part, on the meta-ness of the class.
