### ISSUE TITLE
preferences file not working?

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#94]
I changed the preferences file to enable autocommit, but when I login the `Auto Commit` button displays an disabled:
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/6479e511-e730-461b-b643-26fc88b4871f)
Commit Ids:
```
JadeiteForPharo ce29551
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices e620f34
```

**Comment by ericwinger** [comment]
autocomplete preference code was still marked as to-do
