### ISSUE TITLE
Selecting last category in a class, does not limit methods to ones in that category

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/JadeiteForPharo#95]
For the last category in the category list, the selection of the category does not filter the methods displayed.
Particularly annoying when the last category is Tests...

**Comment by ericwinger** [comment]
Believe this was fixed in a commit earlier than https://github.com/GemTalk/JadeiteForPharo/commit/b23918a9651a4274695d31e096f9cef1a0bf2ef0

@LisaAlmarode should confirm.

**Comment by LisaAlmarode** [comment]
looks okay
