### ISSUE TITLE
Not clear that you are expecting the user to select a load spec from disk ... and you get a file expected error if you select a directory

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/JadeiteForPharo#98]
I think that you should be prompted at this point that you are looking for load spec file ...
![image](https://github.com/GemTalk/JadeiteForPharo/assets/623951/44809aef-301e-43b6-89a4-1dfaca39af92)
and if anything but a load spec is selected the error message (instead of walkback) should be something along the lines that the selected file or directory is not a load spec ...

**Comment by dalehenrich** [comment]
commitIds:
```
JadeiteForPharo ce29551
PharoGemStoneFFI 3575de4
RemoteServiceReplication 371ae8e
---------------------------------------------
RowanClientServices ef59884
```

**Comment by ericwinger** [comment]
https://github.com/GemTalk/JadeiteForPharo/commit/752b2e4a7b0bf272fbb1fc5f92cfe492301d58d0

**Comment by ericwinger** [comment]
The title of the dialog tells the user to choose a load spec file. 
Better error handling and invalid file detection added with an option to debug.
